environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

platform:
  - x86
  - x64

install:
  - ps: Install-Product node 8
  - yarn

cache:
 - "%LOCALAPPDATA%\\Yarn"

test_script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn vscode:prepublish
  - yarn test --silent
#  - .\scripts\test.bat
#  - .\scripts\test-integration.bat

# Don't actually build.
build: off
